### ISSUE TITLE
Enable personal_sign for snaps

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/snaps#1729] opened 2023-09-07 05:52 UTC
Sounds like it’s disabled according to: https://github.com/MetaMask/snaps/pull/1421#issuecomment-1643587896

**Comment by danfinlay** [comment] 2023-09-07 05:53
Are any other signing methods disabled? Maybe make sure signTypedData is available too?

**Comment by FrederikBolding** [comment] 2023-09-07 12:35
@danfinlay `personal_sign` is unblocked! https://github.com/MetaMask/snaps/pull/1601

The other signing methods are currently blocked until we have a reliable way to show snap origins in the UI.

**Comment by firnprotocol** [comment] 2023-09-07 13:26
woah! @danfinlay major apologies for the false alarm / that i wasn't aware of this update. will test shortly and confirm.

@FrederikBolding can I ask whether the update has been released into public Flask?

**Comment by FrederikBolding** [comment] 2023-09-07 13:42
@firnprotocol Ah! That's where the issue lies! Sorry. It will be in the next public Flask release and will roll out later this month. In this repository it is unblocked 😉 

If you are comfortable building the extension yourself you can do that to get it working while we work on the release.

**Comment by firnprotocol** [comment] 2023-09-07 13:51
sure. i will give it a shot.

in retrospect, it looks like there was also a communication issue: though I [had asked](https://github.com/MetaMask/snaps/pull/1421#issuecomment-1643812919) to be notified upon the unblock of `personal_sign`, there was no follow-up in https://github.com/MetaMask/snaps/pull/1421 regarding https://github.com/MetaMask/snaps/pull/1601 — even though the latter was merged just a day after my comment. not sure how i could have known (barring reading every PR).

no hard feelings though—thanks for everything you're doing! i'll report back ASAP if I'm able to confirm access to the method.

**Comment by firnprotocol** [comment] 2023-09-12 16:26
confirmed that i'm able to access this method. thanks again for raising @danfinlay and thanks @FrederikBolding for the great work!

**Comment by FrederikBolding** [comment] 2023-09-13 09:01
Flask v11 (which includes this feature) has been submitted to both Chrome and Firefox and will be rolling out in the very near future. Closing.

**Closed by FrederikBolding** 2023-09-13 09:01 UTC
