### ISSUE TITLE
E2E test: Links in custom UI / Notifications

### ISSUE THREAD

**Issue by GuillaumeRx** [MetaMask/snaps#2021] opened 2023-12-07 14:00 UTC
Ask @GuillaumeRx for implementation details.

**Comment by bowensanders** [comment] 2024-01-19 00:11
This will require pushing a new version of the test-snaps to include changes to the snap(s) used for testing.

**Comment by FrederikBolding** [comment] 2024-03-04 11:21
Duplicate of https://github.com/MetaMask/metamask-extension/issues/22425

**Closed by FrederikBolding** 2024-03-04 11:21 UTC
Labels: snaps-prioritized-2023-oct
