### ISSUE TITLE
Invalid URL: Protocol must be one of: https:, mailto:.

### ISSUE THREAD

**Issue by Janaka-Steph** [MetaMask/snaps#2324] opened 2024-04-10 17:57 UTC
I just installed the snap template with npx @metamask/create-snap my-snap.

Running the demo app using Chrome, clicking "Send Message" fails with:
An error happened: Invalid URL: Protocol must be one of: https:, mailto:.

**Comment by FrederikBolding** [comment] 2024-04-10 19:48
Ah! Sorry, this is caused by a known bug that we are actively fixing. Essentially some over eager validation is currently being triggered for URLs in text that use `http://`.

We will fix this in an upcoming update, but meanwhile you can work around it by stripping these URLs from text shown by your Snap.

**Comment by Montoya** [comment] 2024-04-10 19:52
I think for the demo app, if you strip this line from index.ts within the Snap source code, the bug will go away: 

`text(`Hello, **${origin}**!`),`

**Comment by FrederikBolding** [comment] 2024-04-23 10:13
This is fixed in the latest version of the MetaMask extension (11.14)

**Closed by FrederikBolding** 2024-04-23 10:13 UTC
